# Generated by Django 3.2.22 on 2023-10-13 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0003_alter_temperature_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='value',
            field=models.IntegerField(default='00', max_length=200),
        ),
    ]
